### ISSUE TITLE
special handling for ionic-native

### ISSUE THREAD

**Issue by rapropos** [ionic-zone/update.ionic.zone#2]
Perhaps a warning and link to the v3 upgrade guide would be helpful if "ionic-native" is found as a dependency. There is also a major cliff at 3.6.0, where if the app has any pre-3.6 @ionic-native/plugin packages, and we are going to upgrade @ionic-native/core past 3.6, I believe it would be highly indicated to bring all ionic-native packages up past 3.6 as well. One could make the argument that it would always be helpful to try upgrading all ionic-native packages to match whatever version of core is being recommended, but maybe that's overly aggressive.

**Comment by janpio** [comment]
I have this feature on my list a "Important Changes". I imagine a JSON that contains the package names, "cliff" version numbers and messages that, if "updated over" the "cliff version" triggers the "message" to be displayed.

| `@ionic-native/core` |  3.6.0 |  You should upgrade all other ionic-native packages as well |

Problem is this won't work for the `ionic-native` => `@ionic-native/core`

**Comment by janpio** [comment]
> One could make the argument that it would always be helpful to try upgrading all ionic-native packages to match whatever version of core is being recommended, but maybe that's overly aggressive.

I am undecided on that as well, but I think I will wait until I have some real world `package.json` data to see how many packages people use. As documentation of ionic-native is not archived and in general everything is pretty... "fluid" (as in unstable) in there, I am not sure if this would hurt more than help.

**Comment by janpio** [comment]
Hey @rapropos , do you remember what caused this 3.6 cliff for Ionic Native? Result is "just" that all packages have to uprgaded above 3.6 while it is ok to have different versions in general if they are all <3.6 or >3.6, right?

**Comment by janpio** [comment]
I think I found the responsible Ionic Native change: https://github.com/ionic-team/ionic-native/pull/1425

**Comment by janpio** [comment]
Now implemented at https://update.ionic.zone/
(minus the cliff, because I am not 100% sure why this is happening and so couldn't give a good reason.)
